version: '3.7'

services:
  db:
    container_name: database
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pnp
      - MYSQL_USER=pnp
      - MYSQL_PASSWORD=pnp
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql
    networks:
      - pnp-network

  server:
    container_name: server
    image: sunsuking/pnp-server:latest
    ports:
      - '8080:8080'
    volumes:
      - swagger:/app
    depends_on:
      - db
    networks:
      - pnp-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}

  redis:
    container_name: redis
    image: redis:6.2
    ports:
      - '6379:6379'
    networks:
      - pnp-network

  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    ports:
      - '5050:8080'
    networks:
      - pnp-network
    volumes:
      - swagger:/app
    environment:
      - SWAGGER_JSON=/app/swagger.yaml

volumes:
  database:
  swagger:

networks:
  pnp-network:
    driver: bridge
