import RoomRules from '@/app/(header-footer)/rooms/[id]/components/information/RoomRules';
import type { Meta, StoryObj } from '@storybook/react';

const meta = {
  title: 'Rooms/Information/RoomRules',
  component: RoomRules,
  parameters: {
    layout: 'padded',
  },
} satisfies Meta<typeof RoomRules>;

export default meta;

type Story = StoryObj<typeof RoomRules>;

export const Default: Story = {
  args: {
    checkIn: '15:00',
    checkOut: '11:00',
    checkInType: '셀프 체크인',
    rules: [
      {
        id: 1,
        category: '숙박 중',
        title: '게스트 정원 2명',
        icon: 'SYSTEM_FAMILY',
      },
    ],
    amenities: [
      {
        id: 1,
        category: '욕실',
        title: '헤어드라이어',
        subTitle: null,
        icon: 'SYSTEM_HAIRDRYER',
        available: true,
      },
      {
        id: 2,
        category: '욕실',
        title: '샴푸',
        subTitle: null,
        icon: 'SYSTEM_SHAMPOO',
        available: true,
      },
      {
        id: 3,
        category: '욕실',
        title: '바디워시',
        subTitle: null,
        icon: 'SYSTEM_SOAP',
        available: true,
      },
      {
        id: 4,
        category: '욕실',
        title: '온수',
        subTitle: null,
        icon: 'SYSTEM_HOT_WATER',
        available: true,
      },
      {
        id: 5,
        category: '욕실',
        title: '샤워젤',
        subTitle: null,
        icon: 'SYSTEM_SOAP',
        available: true,
      },
      {
        id: 8,
        category: '냉난방',
        title: '난방',
        subTitle: null,
        icon: 'SYSTEM_THERMOMETER',
        available: true,
      },
      {
        id: 14,
        category: '인터넷 및 업무 공간',
        title: '와이파이',
        subTitle: null,
        icon: 'SYSTEM_WI_FI',
        available: true,
      },
      {
        id: 15,
        category: '인터넷 및 업무 공간',
        title: '업무 전용 공간',
        subTitle: null,
        icon: 'SYSTEM_WORKSPACE',
        available: true,
      },
      {
        id: 16,
        category: '주방 및 식사 공간',
        title: '냉장고',
        subTitle: null,
        icon: 'SYSTEM_REFRIGERATOR',
        available: true,
      },
      {
        id: 20,
        category: '위치 특성',
        title: '해변으로 연결 - 해변 바로 앞',
        subTitle: null,
        icon: 'SYSTEM_BEACH',
        available: true,
      },
      {
        id: 21,
        category: '야외',
        title: '야외 식사 공간',
        subTitle: null,
        icon: 'SYSTEM_ROOFTOP_DECK',
        available: true,
      },
      {
        id: 23,
        category: '주차장 및 기타 시설',
        title: '건물 내 무료 주차',
        subTitle: null,
        icon: 'SYSTEM_MAPS_CAR_RENTAL',
        available: true,
      },
      {
        id: 24,
        category: '서비스',
        title: '장기 숙박 가능',
        subTitle: null,
        icon: 'SYSTEM_CALENDAR',
        available: true,
      },
      {
        id: 25,
        category: '숙소에 없는 시설',
        title: '주방',
        subTitle: null,
        icon: 'SYSTEM_NO_KITCHEN',
        available: false,
      },
      {
        id: 26,
        category: '숙소에 없는 시설',
        title: '세탁기',
        subTitle: null,
        icon: 'SYSTEM_NO_WASHER',
        available: false,
      },
      {
        id: 29,
        category: '아름다운 전망',
        title: '해변 전망',
        subTitle: null,
        icon: 'SYSTEM_BEACH',
        available: true,
      },
      {
        id: 30,
        category: '아름다운 전망',
        title: '바다 전망',
        subTitle: null,
        icon: 'SYSTEM_VIEW_OCEAN',
        available: true,
      },
      {
        id: 31,
        category: '욕실',
        title: '컨디셔너',
        subTitle: null,
        icon: 'SYSTEM_SHAMPOO',
        available: true,
      },
      {
        id: 32,
        category: '침실 및 세탁 시설',
        title: '필수용품',
        subTitle: null,
        icon: 'SYSTEM_TOILETRIES',
        available: true,
      },
      {
        id: 33,
        category: '침실 및 세탁 시설',
        title: '옷걸이',
        subTitle: null,
        icon: 'SYSTEM_HANGERS',
        available: true,
      },
      {
        id: 34,
        category: '침실 및 세탁 시설',
        title: '침구',
        subTitle: null,
        icon: 'SYSTEM_BLANKETS',
        available: true,
      },
      {
        id: 35,
        category: '침실 및 세탁 시설',
        title: '암막 커튼',
        subTitle: null,
        icon: 'SYSTEM_BLACKOUT_SHADES',
        available: true,
      },
      {
        id: 36,
        category: '가족',
        title: '보드게임',
        subTitle: null,
        icon: 'SYSTEM_BOARD_GAMES',
        available: true,
      },
      {
        id: 37,
        category: '냉난방',
        title: '에어컨 - 분리형 무배관 시스템',
        subTitle: null,
        icon: 'SYSTEM_SNOWFLAKE',
        available: true,
      },
      {
        id: 38,
        category: '숙소 안전',
        title: '화재경보기',
        subTitle: null,
        icon: 'SYSTEM_DETECTOR_SMOKE',
        available: true,
      },
      {
        id: 39,
        category: '숙소 안전',
        title: '일산화탄소 경보기',
        subTitle: null,
        icon: 'SYSTEM_DETECTOR_CO',
        available: true,
      },
      {
        id: 40,
        category: '숙소 안전',
        title: '소화기',
        subTitle: null,
        icon: 'SYSTEM_FIRE_EXTINGUISHER',
        available: true,
      },
      {
        id: 41,
        category: '숙소 안전',
        title: '구급 상자',
        subTitle: null,
        icon: 'SYSTEM_FIRST_AID_KIT',
        available: true,
      },
      {
        id: 42,
        category: '주방 및 식사 공간',
        title: '전자레인지',
        subTitle: null,
        icon: 'SYSTEM_MICROWAVE',
        available: true,
      },
      {
        id: 43,
        category: '위치 특성',
        title: '게스트 전용 출입문',
        subTitle: null,
        icon: 'SYSTEM_DOOR',
        available: true,
      },
      {
        id: 44,
        category: '위치 특성',
        title: '리조트 이용',
        subTitle: null,
        icon: 'SYSTEM_MAPS_RESORT',
        available: true,
      },
      {
        id: 45,
        category: '야외',
        title: '공용 뒷마당 – 울타리 완비',
        subTitle: null,
        icon: 'SYSTEM_FLOWER',
        available: true,
      },
      {
        id: 46,
        category: '야외',
        title: '해먹',
        subTitle: null,
        icon: 'SYSTEM_HAMMOCK',
        available: true,
      },
      {
        id: 47,
        category: '야외',
        title: '해수욕 필수품',
        subTitle: null,
        icon: 'SYSTEM_MAPS_RESORT',
        available: true,
      },
      {
        id: 48,
        category: '주차장 및 기타 시설',
        title: '노상 무료 주차',
        subTitle: null,
        icon: 'SYSTEM_MAPS_CAR_RENTAL',
        available: true,
      },
      {
        id: 49,
        category: '서비스',
        title: '여행 가방 보관 가능',
        subTitle: null,
        icon: 'SYSTEM_LUGGAGE_DROP',
        available: true,
      },
      {
        id: 50,
        category: '서비스',
        title: '셀프 체크인',
        subTitle: null,
        icon: 'SYSTEM_KEY',
        available: true,
      },
      {
        id: 51,
        category: '서비스',
        title: '디지털 도어록',
        subTitle: null,
        icon: 'SYSTEM_BUZZER',
        available: true,
      },
      {
        id: 52,
        category: '숙소에 없는 시설',
        title: '숙소 내 실외 보안 카메라',
        subTitle: null,
        icon: 'SYSTEM_NO_SURVEILLANCE',
        available: false,
      },
      {
        id: 53,
        category: '숙소에 없는 시설',
        title: 'TV',
        subTitle: null,
        icon: 'SYSTEM_NO_TV',
        available: false,
      },
    ],
  },
};
