-- Active: 1733640607380@@127.0.0.1@3306@pnp
START TRANSACTION;

SET FOREIGN_KEY_CHECKS = 0;
use pnp;
TRUNCATE TABLE room_reviews;
TRUNCATE TABLE room_amenities;
TRUNCATE TABLE room_rules;
TRUNCATE TABLE room_images;
TRUNCATE TABLE rooms;
TRUNCATE TABLE amenities;
TRUNCATE TABLE rules;
TRUNCATE TABLE sessions;
TRUNCATE TABLE accounts;
TRUNCATE TABLE hosts;
TRUNCATE TABLE tags;
TRUNCATE TABLE host_tags;
TRUNCATE TABLE users;
SET FOREIGN_KEY_CHECKS = 1;

COMMIT;
