insert into pnp.rules (id, category, title, icon) values (1, '숙박 중', '게스트 정원 2명', 'SYSTEM_FAMILY');
insert into pnp.rules (id, category, title, icon) values (2, '숙박 중', '반려동물 동반 불가', 'SYSTEM_NO_PETS');
insert into pnp.rules (id, category, title, icon) values (3, '숙박 중', '파티나 이벤트 금지', 'SYSTEM_NO_EVENTS');
insert into pnp.rules (id, category, title, icon) values (4, '숙박 중', '흡연 금지', 'SYSTEM_SMOKING_NOT_ALLOWED');
insert into pnp.rules (id, category, title, icon) values (5, '숙박 중', '추가 이용규칙', 'SYSTEM_CLIPBOARD');
insert into pnp.rules (id, category, title, icon) values (6, '체크아웃하기 전에', '추가 요청 사항', 'SYSTEM_NOTE_PAPER');
insert into pnp.rules (id, category, title, icon) values (7, '숙박 중', '게스트 정원 4명', 'SYSTEM_FAMILY');
insert into pnp.rules (id, category, title, icon) values (8, '숙박 중', '반려동물 동반 가능', 'SYSTEM_PETS');
insert into pnp.rules (id, category, title, icon) values (9, '숙박 중', '소음 제한 시간대', 'SYSTEM_EVENING');
insert into pnp.rules (id, category, title, icon) values (10, '숙박 중', '상업적 사진 촬영 금지', 'SYSTEM_NO_CAMERA');
insert into pnp.rules (id, category, title, icon) values (11, '숙박 중', '상업적 사진 촬영 가능', 'SYSTEM_CAMERA');
insert into pnp.rules (id, category, title, icon) values (12, '체크아웃하기 전에', '사용한 수건 한곳에 모아놓기', 'SYSTEM_TOWEL');
insert into pnp.rules (id, category, title, icon) values (13, '체크아웃하기 전에', '쓰레기 버리기', 'SYSTEM_TRASH');
insert into pnp.rules (id, category, title, icon) values (14, '체크아웃하기 전에', '가전제품 전원 끄기', 'SYSTEM_POWER_SWITCH');
insert into pnp.rules (id, category, title, icon) values (15, '숙박 중', '게스트 정원 3명', 'SYSTEM_FAMILY');
insert into pnp.rules (id, category, title, icon) values (16, '숙박 중', '게스트 정원 6명', 'SYSTEM_FAMILY');
insert into pnp.rules (id, category, title, icon) values (17, '체크아웃하기 전에', '열쇠 반납하기', 'SYSTEM_HOST_OWNERS');
insert into pnp.rules (id, category, title, icon) values (18, '숙박 중', '게스트 정원 1명', 'SYSTEM_FAMILY');
insert into pnp.rules (id, category, title, icon) values (19, '체크아웃하기 전에', '문 잠그기', 'SYSTEM_LOCK');
insert into pnp.rules (id, category, title, icon) values (20, '숙박 중', '게스트 정원 8명', 'SYSTEM_FAMILY');
insert into pnp.rules (id, category, title, icon) values (21, '숙박 중', '게스트 정원 5명', 'SYSTEM_FAMILY');
insert into pnp.rules (id, category, title, icon) values (22, '숙박 중', '흡연 가능', 'SYSTEM_SMOKING_ALLOWED');
insert into pnp.rules (id, category, title, icon) values (23, '숙박 중', '게스트 정원 10명', 'SYSTEM_FAMILY');
insert into pnp.rules (id, category, title, icon) values (24, '숙박 중', '게스트 정원 7명', 'SYSTEM_FAMILY');
insert into pnp.rules (id, category, title, icon) values (25, '숙박 중', '게스트 정원 12명', 'SYSTEM_FAMILY');
insert into pnp.rules (id, category, title, icon) values (26, '숙박 중', '게스트 정원 14명', 'SYSTEM_FAMILY');
insert into pnp.rules (id, category, title, icon) values (27, '숙박 중', '게스트 정원 15명', 'SYSTEM_FAMILY');
insert into pnp.rules (id, category, title, icon) values (28, '숙박 중', '게스트 정원 13명', 'SYSTEM_FAMILY');
insert into pnp.rules (id, category, title, icon) values (29, '숙박 중', '게스트 정원 9명', 'SYSTEM_FAMILY');
insert into pnp.rules (id, category, title, icon) values (30, '숙박 중', '게스트 정원 11명', 'SYSTEM_FAMILY');
